# Generated by Django 4.2.7 on 2026-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_query_epsilon", models.FloatField(default=1.0)),
                ("used_query_epsilon", models.FloatField(default=0.0)),
                ("total_gradient_epsilon", models.FloatField(default=1.0)),
                ("used_gradient_epsilon", models.FloatField(default=0.0)),
                ("delta", models.FloatField(default=1e-05)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_budget",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_budgets",
            },
        ),
    ]
