# Generated by Django 4.2.7 on 2026-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.5)),
                ("confidence", models.FloatField(default=0.5)),
                ("round_number", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_scores",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "reputation_scores",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReputationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("update", "Update"),
                            ("penalty", "Penalty"),
                            ("reward", "Reward"),
                            ("attack_detected", "Attack Detected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("delta_score", models.FloatField(default=0.0)),
                ("old_score", models.FloatField(default=0.5)),
                ("new_score", models.FloatField(default=0.5)),
                ("reason", models.TextField(blank=True, null=True)),
                ("round_number", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_history",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "reputation_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
