# Generated by Django 4.2.7 on 2026-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(unique=True)),
                ("hash", models.CharField(max_length=64, unique=True)),
                ("previous_hash", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField()),
                ("nonce", models.IntegerField(default=0)),
                ("merkle_root", models.CharField(max_length=64)),
                ("reputation_data", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miner_device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mined_blocks",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "blocks",
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=64, unique=True)),
                ("sender", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=255)),
                ("data", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="blockchain.block",
                    ),
                ),
                (
                    "sender_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_transactions",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainLedger",
            fields=[
                ("entry_id", models.AutoField(primary_key=True, serialize=False)),
                ("fl_round_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=50)),
                ("device_count", models.IntegerField(default=0)),
                (
                    "global_model_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("metadata", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="blockchain.block",
                    ),
                ),
            ],
            options={
                "db_table": "blockchain_ledger",
                "ordering": ["-created_at"],
            },
        ),
    ]
