# Generated by Django 4.2.7 on 2026-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FLRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("round_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("min_participants", models.IntegerField(default=5)),
                ("max_participants", models.IntegerField(default=50)),
                ("current_participants", models.IntegerField(default=0)),
                ("global_model_accuracy", models.FloatField(default=0.0)),
                ("global_model_loss", models.FloatField(default=0.0)),
                (
                    "aggregation_method",
                    models.CharField(default="FedAvg", max_length=50),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fl_rounds",
                "ordering": ["-round_number"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epoch", models.IntegerField()),
                ("batch_accuracy", models.FloatField(default=0.0)),
                ("batch_loss", models.FloatField(default=0.0)),
                ("learning_rate", models.FloatField(default=0.01)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_metrics",
                        to="accounts.device",
                    ),
                ),
                (
                    "fl_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="federated_learning.flround",
                    ),
                ),
            ],
            options={
                "db_table": "training_metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ModelUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("model_weights", models.TextField()),
                ("local_accuracy", models.FloatField(default=0.0)),
                ("local_loss", models.FloatField(default=0.0)),
                ("training_samples", models.IntegerField(default=0)),
                ("is_malicious", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("gradient_norm", models.FloatField(default=0.0)),
                ("privacy_budget_used", models.FloatField(default=0.0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_updates",
                        to="accounts.device",
                    ),
                ),
                (
                    "fl_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="federated_learning.flround",
                    ),
                ),
            ],
            options={
                "db_table": "model_updates",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GlobalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "model_architecture",
                    models.CharField(default="SimpleCNN", max_length=100),
                ),
                ("model_weights", models.TextField()),
                (
                    "model_file_path",
                    models.FileField(blank=True, null=True, upload_to="models/global/"),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("loss", models.FloatField(default=0.0)),
                ("num_parameters", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fl_round",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_model",
                        to="federated_learning.flround",
                    ),
                ),
            ],
            options={
                "db_table": "global_models",
            },
        ),
    ]
