# Generated by Django 4.2.7 on 2026-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fl_round_id", models.CharField(max_length=100)),
                ("fl_round_number", models.IntegerField(default=0)),
                (
                    "attack_type",
                    models.CharField(
                        choices=[
                            ("SAR", "Statistical Attack Replacement"),
                            ("BASR", "Backdoor Attack with Sample Replacement"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_malicious", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attack_logs",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "attack_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fl_round_number", models.IntegerField(default=0)),
                ("gradient_norm", models.FloatField(default=0.0)),
                ("z_score", models.FloatField(default=0.0)),
                ("is_anomalous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_results",
                        to="accounts.device",
                    ),
                ),
            ],
            options={
                "db_table": "anomaly_detection_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
